name: End To End Tests
on:
  pull_request: 
    branches: 
      - main
    types: 
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Setup Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '18.x'
          
      - name: Cache Dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-


      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm i
        env:
          CI: true

      - name: Setup Puppeteer Chrome
        uses: MauFournier/puppeteer-headful-with-commands@v3.0.0

      - name: Run end to end tests
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' npm run test-e2e
        env:
          CI: true